export const Users = [
    {
      id:1,
      profilePicture: "persons/person1.png",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "persons/person2.png",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "persons/person3.webp",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "persons/person4.png",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "persons/person5.avif",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "persons/person6.avif",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "persons/person7.png",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "persons/person8.png",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "persons/person9.png",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "persons/person10.avif",
      username: "Maciej Duraj",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "posts/post1.png",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "posts/post2.png",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "posts/post3.png",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "posts/post4.png",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "posts/post5.png",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "posts/post6.png",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "posts/post7.png",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "posts/post8.png",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "posts/post9.png",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "posts/post10.png",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];